server:
  port: 9192
  
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
      
auth:
  token:
    expirationInMils: 3600000
    jwtSecret: c2VjdXJlS2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw